name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Ensure Go module
        run: go mod tidy

      - name: Perform testing
        run: go test ./... -cover
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code formatting
        run: test -z $(go fmt ./...)
      - name: Ensure Go module
        run: go mod tidy
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1

